[2024-11-19T17:04:33.644+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T17:04:33.660+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_fptshop manual__2024-11-19T15:44:00.418133+00:00 [queued]>
[2024-11-19T17:04:33.666+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_fptshop manual__2024-11-19T15:44:00.418133+00:00 [queued]>
[2024-11-19T17:04:33.666+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-19T17:04:33.676+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): laptop_scraping_tasks.scrape_fptshop> on 2024-11-19 15:44:00.418133+00:00
[2024-11-19T17:04:33.679+0000] {standard_task_runner.py:72} INFO - Started process 65355 to run task
[2024-11-19T17:04:33.682+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'laptop_scraping_tasks.scrape_fptshop', 'manual__2024-11-19T15:44:00.418133+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp6n9tn1sh']
[2024-11-19T17:04:33.682+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask laptop_scraping_tasks.scrape_fptshop
[2024-11-19T17:04:33.735+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.laptop_scraping_tasks.scrape_fptshop manual__2024-11-19T15:44:00.418133+00:00 [running]> on host 9694314923d2
[2024-11-19T17:04:33.823+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='laptop_scraping_tasks.scrape_fptshop' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T15:44:00.418133+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T15:44:00.418133+00:00'
[2024-11-19T17:04:33.824+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T17:04:33.846+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-19T17:04:33.847+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /app/scraper && scrapy crawl fptshop_spider -O ../temp/fptshop_data.json']
[2024-11-19T17:04:33.854+0000] {subprocess.py:86} INFO - Output:
[2024-11-19T17:10:49.355+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-19T17:10:49.357+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-19T17:10:49.363+0000] {process_utils.py:132} INFO - Sending 15 to group 65355. PIDs of all processes in the group: [65363, 65370, 65381, 65355]
[2024-11-19T17:10:49.366+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 65355
[2024-11-19T17:10:49.369+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-19T17:10:49.370+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-11-19T17:10:49.397+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-19T17:10:49.411+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=laptop_scraping_tasks.scrape_fptshop, run_id=manual__2024-11-19T15:44:00.418133+00:00, execution_date=20241119T154400, start_date=20241119T170433, end_date=20241119T171049
[2024-11-19T17:10:49.437+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T17:10:49.630+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=65355, status='terminated', exitcode=2, started='17:04:33') (65355) terminated with exit code 2
[2024-11-19T17:10:49.893+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=65381, status='terminated', started='17:04:34') (65381) terminated with exit code None
[2024-11-19T17:10:50.203+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-11-19T17:10:58.661+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=65370, status='terminated', started='17:04:34') (65370) terminated with exit code None
[2024-11-19T17:10:59.031+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=65363, status='terminated', started='17:04:33') (65363) terminated with exit code None
