[2024-11-05T19:35:07.283+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T19:35:07.391+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.database_tasks.insert_into_cpu_specs_table_sql manual__2024-11-05T18:45:08.073987+00:00 [queued]>
[2024-11-05T19:35:07.398+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.database_tasks.insert_into_cpu_specs_table_sql manual__2024-11-05T18:45:08.073987+00:00 [queued]>
[2024-11-05T19:35:07.399+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T19:35:07.409+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): database_tasks.insert_into_cpu_specs_table_sql> on 2024-11-05 18:45:08.073987+00:00
[2024-11-05T19:35:07.412+0000] {standard_task_runner.py:72} INFO - Started process 29456 to run task
[2024-11-05T19:35:07.416+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'database_tasks.insert_into_cpu_specs_table_sql', 'manual__2024-11-05T18:45:08.073987+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp952df0c_']
[2024-11-05T19:35:07.416+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask database_tasks.insert_into_cpu_specs_table_sql
[2024-11-05T19:35:07.466+0000] {task_command.py:467} INFO - Running <TaskInstance: test_dag.database_tasks.insert_into_cpu_specs_table_sql manual__2024-11-05T18:45:08.073987+00:00 [running]> on host 7f595eb385b7
[2024-11-05T19:35:07.539+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='database_tasks.insert_into_cpu_specs_table_sql' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T18:45:08.073987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T18:45:08.073987+00:00'
[2024-11-05T19:35:07.540+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T19:35:07.559+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/airflow/dags/database/sql_helper.py", line 221, in get_insert_into_cpu_specs_table_sql
    f"'{cpu['L1_instruction_cache']}'" if cpu.get('L1_instruction_cache') != "n/a" else "NULL",
        ~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'L1_instruction_cache'
[2024-11-05T19:35:07.577+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=test_dag, task_id=database_tasks.insert_into_cpu_specs_table_sql, run_id=manual__2024-11-05T18:45:08.073987+00:00, execution_date=20241105T184508, start_date=20241105T193507, end_date=20241105T193507
[2024-11-05T19:35:07.588+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T19:35:07.588+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task database_tasks.insert_into_cpu_specs_table_sql ('L1_instruction_cache'; 29456)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/airflow/dags/database/sql_helper.py", line 221, in get_insert_into_cpu_specs_table_sql
    f"'{cpu['L1_instruction_cache']}'" if cpu.get('L1_instruction_cache') != "n/a" else "NULL",
        ~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'L1_instruction_cache'
[2024-11-05T19:35:07.594+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T19:35:07.609+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
