[2024-11-05T15:48:37.695+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T15:48:37.713+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:48:30.631757+00:00 [queued]>
[2024-11-05T15:48:37.722+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:48:30.631757+00:00 [queued]>
[2024-11-05T15:48:37.722+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T15:48:37.732+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): database_tasks.check_integrity> on 2024-11-05 15:48:30.631757+00:00
[2024-11-05T15:48:37.735+0000] {standard_task_runner.py:72} INFO - Started process 1435 to run task
[2024-11-05T15:48:37.738+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'database_tasks.check_integrity', 'manual__2024-11-05T15:48:30.631757+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpg8jnfn_p']
[2024-11-05T15:48:37.739+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask database_tasks.check_integrity
[2024-11-05T15:48:37.793+0000] {task_command.py:467} INFO - Running <TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:48:30.631757+00:00 [running]> on host e4441a745b1f
[2024-11-05T15:48:37.875+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='database_tasks.check_integrity' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T15:48:30.631757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T15:48:30.631757+00:00'
[2024-11-05T15:48:37.877+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T15:48:37.895+0000] {logging_mixin.py:190} INFO - Connection to PostgreSQL DB successful
[2024-11-05T15:48:37.906+0000] {logging_mixin.py:190} INFO - Error: [Errno 2] No such file or directory: '../../temp/cpu_data.json'
[2024-11-05T15:48:37.907+0000] {python.py:240} INFO - Done. Returned value was: 1
[2024-11-05T15:48:37.933+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T15:48:37.933+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=database_tasks.check_integrity, run_id=manual__2024-11-05T15:48:30.631757+00:00, execution_date=20241105T154830, start_date=20241105T154837, end_date=20241105T154837
[2024-11-05T15:48:37.958+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T15:48:37.973+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T15:48:37.975+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
