[2024-11-05T15:47:10.441+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T15:47:10.456+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:47:05.407653+00:00 [queued]>
[2024-11-05T15:47:10.463+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:47:05.407653+00:00 [queued]>
[2024-11-05T15:47:10.463+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T15:47:10.472+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): database_tasks.check_integrity> on 2024-11-05 15:47:05.407653+00:00
[2024-11-05T15:47:10.475+0000] {standard_task_runner.py:72} INFO - Started process 1430 to run task
[2024-11-05T15:47:10.479+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'database_tasks.check_integrity', 'manual__2024-11-05T15:47:05.407653+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp9coqnv3h']
[2024-11-05T15:47:10.480+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask database_tasks.check_integrity
[2024-11-05T15:47:10.534+0000] {task_command.py:467} INFO - Running <TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:47:05.407653+00:00 [running]> on host b477d4818c6f
[2024-11-05T15:47:10.620+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='database_tasks.check_integrity' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T15:47:05.407653+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T15:47:05.407653+00:00'
[2024-11-05T15:47:10.621+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T15:47:10.640+0000] {logging_mixin.py:190} INFO - Connection to PostgreSQL DB successful
[2024-11-05T15:47:10.649+0000] {logging_mixin.py:190} INFO - Error: [Errno 2] No such file or directory: '../temp/cpu_data.json'
[2024-11-05T15:47:10.650+0000] {python.py:240} INFO - Done. Returned value was: 1
[2024-11-05T15:47:10.676+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T15:47:10.676+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=database_tasks.check_integrity, run_id=manual__2024-11-05T15:47:05.407653+00:00, execution_date=20241105T154705, start_date=20241105T154710, end_date=20241105T154710
[2024-11-05T15:47:10.697+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T15:47:10.712+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T15:47:10.714+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
