[2024-11-19T15:44:01.189+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T15:44:01.207+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.specifications_scraping_tasks.cpu_scrape_task manual__2024-11-19T15:44:00.418133+00:00 [queued]>
[2024-11-19T15:44:01.214+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.specifications_scraping_tasks.cpu_scrape_task manual__2024-11-19T15:44:00.418133+00:00 [queued]>
[2024-11-19T15:44:01.215+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-19T15:44:01.227+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): specifications_scraping_tasks.cpu_scrape_task> on 2024-11-19 15:44:00.418133+00:00
[2024-11-19T15:44:01.230+0000] {standard_task_runner.py:72} INFO - Started process 3687 to run task
[2024-11-19T15:44:01.234+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'specifications_scraping_tasks.cpu_scrape_task', 'manual__2024-11-19T15:44:00.418133+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpyk3bs7qx']
[2024-11-19T15:44:01.235+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask specifications_scraping_tasks.cpu_scrape_task
[2024-11-19T15:44:01.291+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.specifications_scraping_tasks.cpu_scrape_task manual__2024-11-19T15:44:00.418133+00:00 [running]> on host 9694314923d2
[2024-11-19T15:44:01.411+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='specifications_scraping_tasks.cpu_scrape_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T15:44:00.418133+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T15:44:00.418133+00:00'
[2024-11-19T15:44:01.412+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T15:44:01.430+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-19T15:44:01.432+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /app/scraper && scrapy crawl cpu_spider -O ../temp/cpu_data.json']
[2024-11-19T15:44:01.442+0000] {subprocess.py:86} INFO - Output:
[2024-11-19T17:10:49.409+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-19T17:10:49.435+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-19T17:10:49.450+0000] {process_utils.py:132} INFO - Sending 15 to group 3687. PIDs of all processes in the group: [3712, 3687]
[2024-11-19T17:10:49.454+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3687
[2024-11-19T17:10:49.491+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-19T17:10:49.541+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-11-19T17:10:49.645+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-19T17:10:49.674+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=specifications_scraping_tasks.cpu_scrape_task, run_id=manual__2024-11-19T15:44:00.418133+00:00, execution_date=20241119T154400, start_date=20241119T154401, end_date=20241119T171049
[2024-11-19T17:10:49.714+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T17:10:49.761+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3687, status='terminated', exitcode=2, started='15:44:00') (3687) terminated with exit code 2
[2024-11-19T17:10:52.459+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-11-19T17:10:56.864+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3712, status='terminated', started='15:44:01') (3712) terminated with exit code None
