[2024-11-02T17:13:06.424+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T17:13:06.438+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.create_laptop_specs_table manual__2024-11-02T17:13:04.535091+00:00 [queued]>
[2024-11-02T17:13:06.444+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.create_laptop_specs_table manual__2024-11-02T17:13:04.535091+00:00 [queued]>
[2024-11-02T17:13:06.445+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-02T17:13:06.458+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): create_laptop_specs_table> on 2024-11-02 17:13:04.535091+00:00
[2024-11-02T17:13:06.462+0000] {standard_task_runner.py:72} INFO - Started process 27454 to run task
[2024-11-02T17:13:06.464+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_laptop_specs_table', 'manual__2024-11-02T17:13:04.535091+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpk9kqf9i3']
[2024-11-02T17:13:06.466+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask create_laptop_specs_table
[2024-11-02T17:13:06.527+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.create_laptop_specs_table manual__2024-11-02T17:13:04.535091+00:00 [running]> on host 6db704d540cd
[2024-11-02T17:13:06.625+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='create_laptop_specs_table' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T17:13:04.535091+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T17:13:04.535091+00:00'
[2024-11-02T17:13:06.626+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T17:13:06.643+0000] {sql.py:278} INFO - Executing: 
        CREATE TABLE laptop_specs_11_2024 (
            source VARCHAR(255) NOT NULL,
            brand VARCHAR(255),
            name VARCHAR(255) NOT NULL,
            cpu VARCHAR(255),
            vga VARCHAR(255),
            ram_amount INTEGER,
            ram_type VARCHAR(50),
            storage_amount INTEGER,
            storage_type VARCHAR(50),
            webcam_resolution VARCHAR(50),
            screen_size FLOAT,
            screen_resolution VARCHAR(50),
            screen_refresh_rate INTEGER,
            screen_brightness VARCHAR(50),
            battery_capacity FLOAT,
            battery_cells INTEGER,
            weight FLOAT,
            default_os VARCHAR(255),
            warranty INTEGER,
            price DECIMAL(15, 2) NOT NULL,
            width FLOAT,
            depth FLOAT,
            height FLOAT,
            number_usb_a_ports INTEGER,
            number_usb_c_ports INTEGER,
            number_hdmi_ports INTEGER,
            number_ethernet_ports INTEGER,
            number_audio_jacks INTEGER,
            PRIMARY KEY (source, name)
        );
        
[2024-11-02T17:13:06.670+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 279, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 190, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 166, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 158, in get_hook
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2024-11-02T17:13:06.680+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=create_laptop_specs_table, run_id=manual__2024-11-02T17:13:04.535091+00:00, execution_date=20241102T171304, start_date=20241102T171306, end_date=20241102T171306
[2024-11-02T17:13:06.698+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T17:13:06.700+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task create_laptop_specs_table (The conn_id `postgres_default` isn't defined; 27454)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 279, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 190, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 166, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 158, in get_hook
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2024-11-02T17:13:06.732+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-02T17:13:06.750+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.11/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-11-02T17:13:06.760+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-02T17:13:06.763+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
