[2024-11-19T17:07:31.187+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-19T17:07:31.204+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_laptopaz manual__2024-11-19T15:44:00.418133+00:00 [queued]>
[2024-11-19T17:07:31.211+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.laptop_scraping_tasks.scrape_laptopaz manual__2024-11-19T15:44:00.418133+00:00 [queued]>
[2024-11-19T17:07:31.211+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-19T17:07:31.221+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): laptop_scraping_tasks.scrape_laptopaz> on 2024-11-19 15:44:00.418133+00:00
[2024-11-19T17:07:31.224+0000] {standard_task_runner.py:72} INFO - Started process 76237 to run task
[2024-11-19T17:07:31.227+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'laptop_scraping_tasks.scrape_laptopaz', 'manual__2024-11-19T15:44:00.418133+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp2cwbi_5y']
[2024-11-19T17:07:31.228+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask laptop_scraping_tasks.scrape_laptopaz
[2024-11-19T17:07:31.274+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.laptop_scraping_tasks.scrape_laptopaz manual__2024-11-19T15:44:00.418133+00:00 [running]> on host 9694314923d2
[2024-11-19T17:07:31.351+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='laptop_scraping_tasks.scrape_laptopaz' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T15:44:00.418133+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-19T15:44:00.418133+00:00'
[2024-11-19T17:07:31.352+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-19T17:07:31.360+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-19T17:07:31.361+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /app/scraper && scrapy crawl laptopaz_spider -O ../temp/laptopaz_data.json']
[2024-11-19T17:07:31.368+0000] {subprocess.py:86} INFO - Output:
[2024-11-19T17:10:48.445+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-19T17:10:48.455+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-19T17:10:48.475+0000] {process_utils.py:132} INFO - Sending 15 to group 76237. PIDs of all processes in the group: [76245, 76254, 76262, 76398, 76416, 76449, 76626, 76634, 76638, 76643, 76237]
[2024-11-19T17:10:48.486+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 76237
[2024-11-19T17:10:48.496+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-19T17:10:48.501+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-11-19T17:10:48.515+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76626, status='terminated', started='17:07:33') (76626) terminated with exit code None
[2024-11-19T17:10:48.517+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76643, status='terminated', started='17:07:33') (76643) terminated with exit code None
[2024-11-19T17:10:48.518+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76638, status='terminated', started='17:07:33') (76638) terminated with exit code None
[2024-11-19T17:10:48.521+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76634, status='terminated', started='17:07:33') (76634) terminated with exit code None
[2024-11-19T17:10:48.559+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-19T17:10:48.570+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=laptop_scraping_tasks.scrape_laptopaz, run_id=manual__2024-11-19T15:44:00.418133+00:00, execution_date=20241119T154400, start_date=20241119T170731, end_date=20241119T171048
[2024-11-19T17:10:48.598+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-19T17:10:48.620+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76237, status='terminated', exitcode=2, started='17:07:30') (76237) terminated with exit code 2
[2024-11-19T17:10:48.621+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76416, status='terminated', started='17:07:32') (76416) terminated with exit code None
[2024-11-19T17:10:48.624+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76449, status='terminated', started='17:07:32') (76449) terminated with exit code None
[2024-11-19T17:10:48.819+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76262, status='terminated', started='17:07:31') (76262) terminated with exit code None
[2024-11-19T17:10:48.820+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76398, status='terminated', started='17:07:32') (76398) terminated with exit code None
[2024-11-19T17:10:51.267+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-11-19T17:10:54.808+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76254, status='terminated', started='17:07:31') (76254) terminated with exit code None
[2024-11-19T17:10:55.578+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=76245, status='terminated', started='17:07:31') (76245) terminated with exit code None
