[2024-11-05T15:42:58.867+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T15:42:58.881+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:42:53.986190+00:00 [queued]>
[2024-11-05T15:42:58.887+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:42:53.986190+00:00 [queued]>
[2024-11-05T15:42:58.888+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T15:42:58.897+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): database_tasks.check_integrity> on 2024-11-05 15:42:53.986190+00:00
[2024-11-05T15:42:58.900+0000] {standard_task_runner.py:72} INFO - Started process 2110 to run task
[2024-11-05T15:42:58.903+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'database_tasks.check_integrity', 'manual__2024-11-05T15:42:53.986190+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp_kny0k4o']
[2024-11-05T15:42:58.905+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask database_tasks.check_integrity
[2024-11-05T15:42:58.947+0000] {task_command.py:467} INFO - Running <TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-05T15:42:53.986190+00:00 [running]> on host 1920977ffba2
[2024-11-05T15:42:59.010+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='database_tasks.check_integrity' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T15:42:53.986190+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T15:42:53.986190+00:00'
[2024-11-05T15:42:59.011+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T15:42:59.024+0000] {logging_mixin.py:190} INFO - Connection to PostgreSQL DB successful
[2024-11-05T15:42:59.188+0000] {logging_mixin.py:190} INFO - Error executing query: [Errno 2] No such file or directory: './temp/laptop_data.json'
[2024-11-05T15:42:59.188+0000] {python.py:240} INFO - Done. Returned value was: 0
[2024-11-05T15:42:59.213+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T15:42:59.214+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=database_tasks.check_integrity, run_id=manual__2024-11-05T15:42:53.986190+00:00, execution_date=20241105T154253, start_date=20241105T154258, end_date=20241105T154259
[2024-11-05T15:42:59.246+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T15:42:59.260+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T15:42:59.262+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
