[2024-11-02T17:46:13.934+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T17:46:13.949+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.create_laptop_specs_table manual__2024-11-02T17:46:12.788032+00:00 [queued]>
[2024-11-02T17:46:13.957+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.create_laptop_specs_table manual__2024-11-02T17:46:12.788032+00:00 [queued]>
[2024-11-02T17:46:13.957+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-02T17:46:13.969+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): create_laptop_specs_table> on 2024-11-02 17:46:12.788032+00:00
[2024-11-02T17:46:13.974+0000] {standard_task_runner.py:72} INFO - Started process 6128 to run task
[2024-11-02T17:46:13.978+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_laptop_specs_table', 'manual__2024-11-02T17:46:12.788032+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpuo4u63ka']
[2024-11-02T17:46:13.981+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask create_laptop_specs_table
[2024-11-02T17:46:14.037+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.create_laptop_specs_table manual__2024-11-02T17:46:12.788032+00:00 [running]> on host 0dd2646d10a8
[2024-11-02T17:46:14.146+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='create_laptop_specs_table' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T17:46:12.788032+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T17:46:12.788032+00:00'
[2024-11-02T17:46:14.148+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T17:46:14.164+0000] {sql.py:278} INFO - Executing: 
        CREATE TABLE laptop_specs_11_2024 (
            source VARCHAR(255) NOT NULL,
            brand VARCHAR(255),
            name VARCHAR(255) NOT NULL,
            cpu VARCHAR(255),
            vga VARCHAR(255),
            ram_amount INTEGER,
            ram_type VARCHAR(50),
            storage_amount INTEGER,
            storage_type VARCHAR(50),
            webcam_resolution VARCHAR(50),
            screen_size FLOAT,
            screen_resolution VARCHAR(50),
            screen_refresh_rate INTEGER,
            screen_brightness VARCHAR(50),
            battery_capacity FLOAT,
            battery_cells INTEGER,
            weight FLOAT,
            default_os VARCHAR(255),
            warranty INTEGER,
            price DECIMAL(15, 2) NOT NULL,
            width FLOAT,
            depth FLOAT,
            height FLOAT,
            number_usb_a_ports INTEGER,
            number_usb_c_ports INTEGER,
            number_hdmi_ports INTEGER,
            number_ethernet_ports INTEGER,
            number_audio_jacks INTEGER,
            PRIMARY KEY (source, name)
        );
        
[2024-11-02T17:46:14.183+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-02T17:46:14.197+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-02T17:46:14.211+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 485, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 609, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2024-11-02T17:46:14.230+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_dag, task_id=create_laptop_specs_table, run_id=manual__2024-11-02T17:46:12.788032+00:00, execution_date=20241102T174612, start_date=20241102T174613, end_date=20241102T174614
[2024-11-02T17:46:14.245+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T17:46:14.246+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task create_laptop_specs_table (could not translate host name "postgres" to address: Name or service not known
; 6128)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 485, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 609, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2024-11-02T17:46:14.280+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-02T17:46:14.297+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.11/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-11-02T17:46:14.308+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-02T17:46:14.311+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
